# Generated by Django 5.2.4 on 2025-07-13 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForbiddenWord',
            fields=[
                ('ID', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
