# Generated by Django 4.2.14 on 2025-07-15 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forbidden', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forbiddenword',
            old_name='ID',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='forbiddenword',
            old_name='Name',
            new_name='word',
        ),
    ]
