# Generated by Django 5.2.4 on 2025-07-16 22:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='PARENT_COMMENT_ID',
            new_name='PARENT_COMMENT',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='POST_ID',
            new_name='POST',
        ),
        migrations.AddField(
            model_name='comment',
            name='USER',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
